# Setup
title: "Le Cours d'Informatique Manquant"
#url: https://missing.csail.mit.edu
url: https://ucl-ingi.github.io
baseurl: /missing-semester

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
# timezone: America/New_York
# analytics:
#  tracking_id: G-P7WVHD84D1

collections:
  '2019':
    output: true
  '2020':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - _2020/metaprogramming.md
  - _2020/potpourri.md
  - _2020/security.md
  - _2020/version-control.md
  - _2020/editors.md
  - _2020/debugging-profiling.md
  - _2020/data-wrangling.md
  - _2020/qa.md
  - _2020/command-line.md
  - _2020/shell-tools.md
